### ISSUE TITLE
`numpy` version

### ISSUE THREAD

**Issue by kavanase** [conda-forge/hiphive-feedstock#9]
### Comment:

Hi @jan-janssen!
Sorry to be bugging, but I'm having some issues updating our `conda-forge` package for `ShakeNBreak`, which depends on `hiphive`. It seems to be a `numpy` issue. In `hiphive` `v1.2` the `numpy` requirement is `>=1.18` (https://gitlab.com/materials-modeling/hiphive/-/blob/master/setup.py?ref_type=heads), but in the `conda-forge` `meta.yaml` recipe here it's `<1.21,>=1.12` (which I think is where our issues are coming from).

If you get a chance at some point, would you be able to update this please?
Thanks!

**Comment by jan-janssen** [comment]
I updated the dependencies, the new version should be available in approximately one hour. If you still have issues feel free to reopen the pull request.

**Comment by kavanase** [comment]
@jan-janssen great, thanks! 😃

**Comment by erhart1** [comment]
Thanks @jan-janssen
